### ISSUE TITLE
Question about reproducing code

### ISSUE THREAD

**Issue by IMGresearcher** [amycanada/Mesh_Generation_Dr_Zeng#1]
Hello, Amy! 

> This work is amazing. We are very excited to see the use of reinforcement learning techniques to generate quadrilateral meshes. Our research group is very interested in your research, can you leave a contact information for communication? We want to reproduce these codes.

**Comment by amycanada** [comment]
Amy Chen has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [amycanada/Mesh_Generation_Dr_Zeng] Question about reproducing code (Issue #1) <https://confidential-mail.google.com/msg/AJ05YhefPyEfzTdj6ezN-0KAHuh4Eag5prz78trPEWGtWTpOKa50_sWSegtKsG7uXCfrqyS8syOYt9ZAgd2IMAPWBSF6cg8IBTmtNzv3Ur_vEGgrysDqP0bZeiATQ-ahb24rnvH-ETLeZaGHu0DmICzJYGiff9nA7cWzFqvPebjJjD9op7SeKbFR653Ekvfcerl3H-HV4K294A==>

This message was sent on Aug 18, 2023 at 10:34:46 AM PDT
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/AJ05YhefPyEfzTdj6ezN-0KAHuh4Eag5prz78trPEWGtWTpOKa50_sWSegtKsG7uXCfrqyS8syOYt9ZAgd2IMAPWBSF6cg8IBTmtNzv3Ur_vEGgrysDqP0bZeiATQ-ahb24rnvH-ETLeZaGHu0DmICzJYGiff9nA7cWzFqvPebjJjD9op7SeKbFR653Ekvfcerl3H-HV4K294A==>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]

**Comment by amycanada** [comment]
您的 Google 验证码是 369732

**Comment by IMGresearcher** [comment]
Thank you！
